#!/bin/bash
#
# drun
#  Description: 
#  Relay arbritary commands into docker container
#

unamestr="$(uname)"
module=${PWD}
drunprops=""
docker_volume_mounts=()
docker_working_dir=()
docker_options=()
OLD_IFS=$IFS
  
if [[ "$unamestr" == "Linux" ]]; then
  drunprops="drun.linux.properties"
elif [[ "$unamestr" == "Darwin" ]]; then
  drunprops="drun.osx.properties" 
else
  echo "Unsupported platform!!"; exit 1; 
fi

while [[ -d "${module}" ]]
do
  project_props="${module}/${drunprops}"
  if [[ -f "$project_props" ]]; then
    . "${module}/${drunprops}"
    break
  fi
  module=${module%/*}  
done

if [ -z "$image" ]; then
  image="ubuntu:16.04"
fi
  
if [ -n "$volumes" ]; then
  IFS=,
  for i in $volumes
  do
    docker_volume_mounts+=("-v" "$i")  
  done    
fi

if [ -n "$workingdir" ]; then
  docker_working_dir=("-w" "$workingdir")
fi

if [ -n "$options" ]; then
  for option in $options
  do
    docker_options+=("$option")  
  done    

fi

IFS=$OLD_IFS
docker run -t --rm \
  "${docker_volume_mounts[@]}" \
  "${docker_working_dir[@]}" \
  --net=host \
  "${docker_options[@]}" \
  "$image" /bin/bash -c "$*"
exit $?
